baseURL = "https://almondfarm.us/"
languageCode = "en-us"
title = "Almond Farm"

[params]
  description = "A lifestyle site by friends, for friends."
  tagline = "get on farming"
  tabTitle = "ALMONDS!"

[menu]
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    name = "Cooking"
    url = "/cooking/"
    weight = 2
  [[menu.main]]
    name = "Music"
    url = "/music/"
    weight = 3
  [[menu.main]]
    name = "Books"
    url = "/books/"
    weight = 4
  [[menu.main]]
    name = "Farming"
    url = "/farming/"
    weight = 5
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 6
  [[menu.main]]
    name = "Gaming"
    url = "/gaming/"
    weight = 7
  [[menu.main]]
    name = "Art"
    url = "/art/"
    weight = 8
  [[menu.main]]
    name = "Movies"
    url = "/movies/"
    weight = 9
  [[menu.main]]
    name = "Drinks"
    url = "/drinks/"
    weight = 10
  [[menu.main]]
    name = "Brain"
    url = "/brain/"
    weight = 11
  [[menu.main]]
    name = "Body"
    url = "/body/"
    weight = 12
  [[menu.main]]
    name = "Gadgets"
    url = "/gadgets/"
    weight = 13
  [[menu.main]]
    name = "Videos"
    url = "/videos/"
    weight = 14
  [[menu.main]]
    name = "Calendar"
    url = "/calendar/"
    weight = 15
  [[menu.main]]
    name = "Markets"
    url = "/markets/"
    weight = 16
  [[menu.main]]
    name = "Dingers"
    url = "/dinger-palooza/"
    weight = 17
  [[menu.main]]
    name = "News"
    url = "/news/"
    weight = 18
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 19

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
