"""One-shot script: patches project_ideas into data/api_map.yaml for all APIs."""
import yaml, pathlib, sys

IDEAS = {
    # Sky & Earth
    "OpenWeatherMap":          ["Current conditions widget for the farm's zip code",
                                "Rain alert banner for irrigation scheduling on Farming page"],
    "NOAA Climate Data Online":["Historical frost dates chart for almond bloom risk on Farming",
                                "Multi-decade Central Valley rainfall chart on Farming page"],
    "USGS Earthquake Hazards": ["Real-time Central Valley quake ticker on Farming page",
                                "Seismic event map embedded in Farming page context"],
    "AirNow":                  ["Wildfire smoke AQI alert during almond harvest season",
                                "Air quality badge in Farming page header"],
    "OpenAQ":                  ["Farm-local air quality index in Farming sidebar",
                                "Global AQI comparison widget in Brain Lab"],
    "Sunrise-Sunset":          ["Daylight hours bar display on Farming page header",
                                "Golden hour countdown for farm photography planning"],
    # Space
    "NASA APOD":               ["Daily astronomy photo rotating in Art section",
                                "Weekly space image gallery in Art section"],
    "NASA EONET":              ["Active California wildfire event feed on Farming page",
                                "Natural disaster map in Farming sidebar"],
    "NASA Mars Rover Photos":  ["Mars rover photo gallery in Art section",
                                "Daily rover image widget in Brain Lab"],
    "NASA NEO":                ["Asteroid close-approach ticker in Brain Lab",
                                "Near-Earth object countdown widget in Brain section"],
    "SpaceX API":              ["Upcoming launch countdown widget in Brain Lab",
                                "Launch history timeline in Brain or Gaming section"],
    "Open Notify (ISS)":       ["ISS pass times over the farm's coordinates in Farming",
                                "Live ISS position tracker in Brain Lab"],
    "Le Système Solaire":      ["Solar system data cards in Brain Lab experiments",
                                "Planet fact comparison widget in Brain section"],
    # Living Things
    "iNaturalist":             ["Wildlife sightings near the almond farm on Farming page",
                                "Native species observation log in Farming section"],
    "GBIF":                    ["Biodiversity count for the farm's county in Farming",
                                "Native California species reference on Farming page"],
    "Open Food Facts":         ["Ingredient sourcing badges on Cooking recipe cards",
                                "Allergen lookup widget in Cooking section"],
    "USDA FoodData Central":   ["Macro breakdown panel auto-added to Cooking recipes",
                                "Nutrition label for farm-grown produce in Cooking"],
    "TheDogAPI":               ["Dog breed of the week card in Body section",
                                "Random dog photo widget in Brain Lab experiments"],
    "TheCatAPI":               ["Random cat image widget in Brain Lab",
                                "Cat breed explorer in Body section"],
    "PokeAPI":                 ["Pokédex lookup tool in Gaming section",
                                "Daily Pokémon card in Gaming section"],
    # Culture & Knowledge
    "Open Library":            ["Book cover art fetcher for the Books reading list",
                                "Author bio lookup linked from Books page entries"],
    "Google Books":            ["Preview links and synopsis enrichment for Books list",
                                "Book search widget in Brain Lab"],
    "MusicBrainz":             ["Album tracklist and release info for Music page entries",
                                "Artist discography explorer linked from Music page"],
    "Last.fm":                 ["Recently scrobbled tracks widget on Music page",
                                "Similar artist recommendations on Music page"],
    "Discogs":                 ["Vinyl record value lookup in Gadgets section",
                                "Release discography with dates on Music page"],
    "TheMovieDB (TMDB)":       ["Movie poster grid in the Movies section",
                                "Now-playing feed for Movies section header"],
    "Open Trivia DB":          ["Daily trivia question widget in Brain Lab",
                                "Category quiz game in Brain section"],
    "Wikidata":                ["Structured fact sidebar for farming-history blog posts",
                                "Entity fact panel in Brain Lab SPARQL explorer"],
    "Wikipedia REST":          ["Article summary cards linked from blog posts",
                                "Random article discovery widget in Brain Lab"],
    "Harvard Art Museums":     ["Rotating art discovery feature in Art section",
                                "Color-palette artwork finder in Art section"],
    "Met Museum":              ["Daily artwork from open collection in Art section",
                                "Department explorer as Art section navigation"],
    "Rijksmuseum":             ["Dutch Golden Age painting gallery in Art section",
                                "Rembrandt/Vermeer spotlight cards in Art section"],
    # Words & Language
    "Datamuse":                ["Rhyme finder for experimental poetry in Brain Lab",
                                "Word association explorer widget in Brain section"],
    "Free Dictionary API":     ["Word lookup hover cards in Blog posts",
                                "Daily word definition widget in Brain Lab"],
    "Wordnik":                 ["Word-of-the-day rotating in site footer",
                                "Etymology context for unusual words in blog posts"],
    "PoetryDB":                ["Random poem widget on Books or Brain page",
                                "Poet of the week feature in Books section"],
    "Project Gutenberg":       ["Classic book recommendations on Books page",
                                "Public domain text excerpt widget in Brain Lab"],
    "Quotable":                ["Rotating quote below visitor counter in footer",
                                "Farming-writer quotes on Farming page header"],
    # Civic & Government
    "US Census Bureau":        ["Central Valley ag demographics sidebar on Farming",
                                "California population data chart in Brain Lab"],
    "Data.gov":                ["USDA almond crop statistics on Farming page",
                                "Federal climate dataset feeds for farm planning tools"],
    "Congress.gov API":        ["Farm bill and water rights tracker on Farming page",
                                "Agricultural subsidy bill status in Farming sidebar"],
    "Open States":             ["California water rights legislation tracker on Farming",
                                "CA ag policy bill status widget in Farming section"],
    "FEC":                     ["Ag industry PAC spending lookup in Brain Lab",
                                "Big ag donor tracking in Civic Brain section"],
    "BLS":                     ["Farm labor wage index chart on Farming page",
                                "CPI food index on Cooking or Markets page"],
    "World Bank":              ["Global almond trade volume chart on Farming page",
                                "Agricultural GDP comparison widget in Brain section"],
    "UN Comtrade":             ["Almond export volume by destination country on Farming",
                                "US commodity flow chart in Farming section"],
    # Sports
    "MLB Stats API":           ["A's or Giants score ticker in Gaming section",
                                "Live MLB standings table in Gaming section"],
    "NBA Stats":               ["Warriors standings card in Gaming section",
                                "NBA player stat lookup in Gaming section"],
    "TheSportsDB":             ["Multi-sport scores dashboard in Gaming section",
                                "Sport team info cards in Gaming section"],
    "Football-data.org":       ["Champions League standings widget in Brain Lab",
                                "Premier League table widget in Gaming section"],
    "ESPN (unofficial)":       ["Daily sports headlines sidebar in Gaming section",
                                "Score ticker across major sports in Gaming"],
    # Maps & Place
    "OpenStreetMap / Overpass":["Farm location map with nearby amenities on About page",
                                "Orchard infrastructure map embedded in Farming page"],
    "Nominatim":               ["Address lookup for farm visitor directions page",
                                "Place name geocoder tool in Brain Lab"],
    "Open Elevation":          ["Farm terrain elevation profile chart on Farming page",
                                "Almond orchard topography display in Farming"],
    "GeoNames":                ["Farm timezone and region info in Farming page header",
                                "Local place name context data in Farming section"],
    "REST Countries":          ["Country fact cards in a future World or Brain section",
                                "Country data lookup widget in Brain Lab"],
    "IP-API":                  ["Visitor location for weather widget personalization",
                                "Anonymous visitor origin map in Brain Lab"],
    # Money & Markets
    "Alpha Vantage":           ["Almond commodity price chart on Farming page",
                                "Agricultural ETF tracker in Markets section"],
    "CoinGecko":               ["Crypto price ticker in Brain Lab or Gadgets section",
                                "Top 10 coins widget in Markets or Brain section"],
    "ExchangeRate.host":       ["Currency converter widget in Gadgets section",
                                "USD rate table on Markets page"],
    "Open Exchange Rates":     ["Live forex rates for almond export context on Farming",
                                "Multi-currency rate table in Markets dashboard"],
    "Yahoo Finance (unofficial)":["Ag company stock tracker in Farming or Markets",
                                  "Informal equity lookup tool in Brain Lab"],
    # Transit & Infrastructure
    "Transit.land":            ["Nearest transit options from farm for visitor page",
                                "Transit route finder for farm trip planning"],
    "Transport for London":    ["TfL live status demo widget in Brain Lab",
                                "London tube arrivals as live API demo in Brain"],
    "WMATA":                   ["DC Metro arrivals demo widget in Brain Lab",
                                "Transit API comparison demo in Brain section"],
    "OpenSky Network":         ["Live aircraft over the farm's airspace on Farming",
                                "Central Valley flight tracker in Brain Lab"],
    "ADS-B Exchange":          ["Real-time military flight map in Brain Lab",
                                "Unfiltered aircraft data experiment in Brain section"],
    # Dev & Social
    "GitHub REST":             ["This site's recent commit history widget in Brain Lab",
                                "Open source project showcase in Gadgets section"],
    "HackerNews":              ["Top HN stories sidebar in Brain Lab section",
                                "Tech news digest in Brain Lab or Gadgets"],
    "Lichess":                 ["Daily chess puzzle widget in Gaming section",
                                "Opening explorer tool in Gaming section"],
    "Chess.com":               ["Chess leaderboard widget in Gaming section",
                                "Puzzle of the day in Gaming section"],
    "CocktailDB":              ["Cocktail recipe card grid in Drinks section",
                                "Random cocktail of the day on Drinks page header"],
}

path = pathlib.Path("data/api_map.yaml")
data = yaml.safe_load(path.read_text())

patched = 0
for cluster in data["clusters"]:
    for api in cluster["apis"]:
        if api["name"] in IDEAS and not api.get("project_ideas"):
            api["project_ideas"] = IDEAS[api["name"]]
            patched += 1

path.write_text(yaml.dump(data, allow_unicode=True, sort_keys=False, default_flow_style=False, width=120))
print(f"Patched {patched} APIs.")
